In [1]:
print("Hello World")

Hello World

In [5]:
import kaggle

In [7]:
!kaggle datasets download dillonmyrick/bike-store-sample-database -f brands.csv

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading brands.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/120 [00:00<?, ?B/s]
100%|██████████| 120/120 [00:00<00:00, 262kB/s]

In [8]:
!kaggle datasets download dillonmyrick/bike-store-sample-database -f categories.csv

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading categories.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/162 [00:00<?, ?B/s]
100%|██████████| 162/162 [00:00<00:00, 403kB/s]

In [9]:
!kaggle datasets download dillonmyrick/bike-store-sample-database -f customers.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f order_items.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f orders.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f products.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f staffs.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f stocks.csv
!kaggle datasets download dillonmyrick/bike-store-sample-database -f stores.csv

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading customers.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/125k [00:00<?, ?B/s]
100%|██████████| 125k/125k [00:00<00:00, 260MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading order_items.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/110k [00:00<?, ?B/s]
100%|██████████| 110k/110k [00:00<00:00, 129MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading orders.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/75.5k [00:00<?, ?B/s]
100%|██████████| 75.5k/75.5k [00:00<00:00, 129MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading products.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/17.0k [00:00<?, ?B/s]
100%|██████████| 17.0k/17.0k [00:00<00:00, 31.7MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading staffs.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/726 [00:00<?, ?B/s]
100%|██████████| 726/726 [00:00<00:00, 1.29MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading stocks.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/8.57k [00:00<?, ?B/s]
100%|██████████| 8.57k/8.57k [00:00<00:00, 16.1MB/s]

Dataset URL: https://www.kaggle.com/datasets/dillonmyrick/bike-store-sample-database
License(s): other
Downloading stores.csv to f:\sql\project9\Bike industry analysis

  0%|          | 0.00/330 [00:00<?, ?B/s]
100%|██████████| 330/330 [00:00<00:00, 895kB/s]

In [16]:
with open('brands.csv', 'rb') as f:
    print(f.read(4))

b'bran'

In [18]:
import pandas as pd
df=pd.read_csv("brands.csv")
df.head(10)

   brand_id    brand_name
0         1       Electra
1         2          Haro
2         3        Heller
3         4   Pure Cycles
4         5       Ritchey
5         6       Strider
6         7  Sun Bicycles
7         8         Surly
8         9          Trek

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   brand_id    9 non-null      int64
 1   brand_name  9 non-null      object
dtypes: int64(1), object(1)
memory usage: 276.0+ bytes

In [20]:
df.describe()

       brand_id
count  9.000000
mean   5.000000
std    2.738613
min    1.000000
25%    3.000000
50%    5.000000
75%    7.000000
max    9.000000

In [21]:
df.isnull().sum()

brand_id      0
brand_name    0
dtype: int64

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df1=pd.read_csv("categories.csv")
df1.head()

   category_id        category_name
0            1    Children Bicycles
1            2     Comfort Bicycles
2            3    Cruisers Bicycles
3            4  Cyclocross Bicycles
4            5       Electric Bikes

In [24]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   category_id    7 non-null      int64
 1   category_name  7 non-null      object
dtypes: int64(1), object(1)
memory usage: 244.0+ bytes

In [25]:
df1.describe()

       category_id
count     7.000000
mean      4.000000
std       2.160247
min       1.000000
25%       2.500000
50%       4.000000
75%       5.500000
max       7.000000

In [26]:
df1.isnull().sum()

category_id      0
category_name    0
dtype: int64

In [27]:
df1.duplicated().sum()

np.int64(0)

In [28]:
df2=pd.read_csv("customers.csv")
df2.head()

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820

In [29]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1445 entries, 0 to 1444
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  1445 non-null   int64
 1   first_name   1445 non-null   object
 2   last_name    1445 non-null   object
 3   phone        178 non-null    object
 4   email        1445 non-null   object
 5   street       1445 non-null   object
 6   city         1445 non-null   object
 7   state        1445 non-null   object
 8   zip_code     1445 non-null   int64
dtypes: int64(2), object(7)
memory usage: 101.7+ KB

In [30]:
df2.describe()

       customer_id      zip_code
count  1445.000000   1445.000000
mean    723.000000  34200.015225
std     417.279882  34733.933551
min       1.000000  10002.000000
25%     362.000000  11419.000000
50%     723.000000  11967.000000
75%    1084.000000  76110.000000
max    1445.000000  95993.000000

In [34]:
df2.isnull().sum()

customer_id    0
first_name     0
last_name      0
phone          0
email          0
street         0
city           0
state          0
zip_code       0
dtype: int64

In [33]:
df2["phone"]=df2["phone"].fillna("Not given")

In [35]:
df2.duplicated().sum()

np.int64(0)

In [36]:
df3=pd.read_csv("order_items.csv")
df3.head()

   order_id  item_id  product_id  quantity  list_price  discount
0         1        1          20         1      599.99      0.20
1         1        2           8         2     1799.99      0.07
2         1        3          10         2     1549.00      0.05
3         1        4          16         2      599.99      0.05
4         1        5           4         1     2899.99      0.20

In [37]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4722 entries, 0 to 4721
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   order_id    4722 non-null   int64
 1   item_id     4722 non-null   int64
 2   product_id  4722 non-null   int64
 3   quantity    4722 non-null   int64
 4   list_price  4722 non-null   float64
 5   discount    4722 non-null   float64
dtypes: float64(2), int64(4)
memory usage: 221.5 KB

In [38]:
df3.describe()

,order_id,item_id,product_id,quantity,list_price,discount
count,4722.000000,4722.000000,4722.000000,4722.000000,4722.000000,4722.000000
mean,821.265354,2.262601,59.366158,1.498941,1212.707872,0.105373
std,465.152168,1.199129,67.312708,0.500052,1352.798257,0.058119
min,1.000000,1.000000,2.000000,1.000000,89.990000,0.050000
25%,423.250000,1.000000,14.000000,1.000000,429.000000,0.050000
50%,828.500000,2.000000,28.000000,1.000000,599.990000,0.085000
75%,1226.000000,3.000000,84.000000,2.000000,1549.000000,0.200000
max,1615.000000,5.000000,315.000000,2.000000,11999.990000,0.200000

In [39]:
df3.isnull().sum()

order_id      0
item_id       0
product_id    0
quantity      0
list_price    0
discount      0
dtype: int64

In [40]:
df3.duplicated().sum()

np.int64(0)

In [46]:
df4=pd.read_csv("orders.csv")
df4.head(20)

,order_id,customer_id,order_status,order_date,required_date,shipped_date,store_id,staff_id
0,1,259,4,2016-01-01,2016-01-03,2016-01-03,1,2
1,2,1212,4,2016-01-01,2016-01-04,2016-01-03,2,6
2,3,523,4,2016-01-02,2016-01-05,2016-01-03,2,7
3,4,175,4,2016-01-03,2016-01-04,2016-01-05,1,3
4,5,1324,4,2016-01-03,2016-01-06,2016-01-06,2,6
5,6,94,4,2016-01-04,2016-01-07,2016-01-05,2,6
6,7,324,4,2016-01-04,2016-01-07,2016-01-05,2,6
7,8,1204,4,2016-01-04,2016-01-05,2016-01-05,2,7
8,9,60,4,2016-01-05,2016-01-08,2016-01-08,1,2
9,10,442,4,2016-01-05,2016-01-06,2016-01-06,2,6
10,11,1326,4,2016-01-05,2016-01-08,2016-01-07,2,7
11,12,91,4,2016-01-06,2016-01-08,2016-01-09,1,2
12,13,873,4,2016-01-08,2016-01-11,2016-01-11,2,6
13,14,258,4,2016-01-09,2016-01-11,2016-01-12,1,3
14,15,450,4,2016-01-09,2016-01-10,2016-01-12,2,7
15,16,552,4,2016-01-12,2016-01-15,2016-01-15,1,3
16,17,1175,4,2016-01-12,2016-01-14,2016-01-14,1,3
17,18,541,4,2016-01-14,2016-01-17,2016-01-15,1,3
18,19,696,4,2016-01-14,2016-01-17,2016-01-16,1,2
19,20,923,4,2016-01-14,2016-01-16,2016-01-17,1,2

In [42]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1615 entries, 0 to 1614
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       1615 non-null   int64
 1   customer_id    1615 non-null   int64
 2   order_status   1615 non-null   int64
 3   order_date     1615 non-null   object
 4   required_date  1615 non-null   object
 5   shipped_date   1445 non-null   object
 6   store_id       1615 non-null   int64
 7   staff_id       1615 non-null   int64
dtypes: int64(5), object(3)
memory usage: 101.1+ KB

In [43]:
df4.describe()

          order_id  customer_id  order_status     store_id     staff_id
count  1615.000000  1615.000000   1615.000000  1615.000000  1615.000000
mean    808.000000   654.171517      3.778947     1.892260     5.855108
std     466.354658   443.229967      0.693430     0.558395     1.913899
min       1.000000     1.000000      1.000000     1.000000     2.000000
25%     404.500000   237.000000      4.000000     2.000000     6.000000
50%     808.000000   638.000000      4.000000     2.000000     6.000000
75%    1211.500000  1041.500000      4.000000     2.000000     7.000000
max    1615.000000  1445.000000      4.000000     3.000000     9.000000

In [44]:
df4.isnull().sum()

order_id           0
customer_id        0
order_status       0
order_date         0
required_date      0
shipped_date     170
store_id           0
staff_id           0
dtype: int64

In [47]:
df4.duplicated().sum()

np.int64(0)

In [48]:
df5=pd.read_csv("products.csv")
df5.head()

,product_id,product_name,brand_id,category_id,model_year,list_price
0,1,Trek 820 - 2016,9,6,2016,379.99
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99

In [49]:
df5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 321 entries, 0 to 320
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    321 non-null    int64
 1   product_name  321 non-null    object
 2   brand_id      321 non-null    int64
 3   category_id   321 non-null    int64
 4   model_year    321 non-null    int64
 5   list_price    321 non-null    float64
dtypes: float64(1), int64(4), object(1)
memory usage: 15.2+ KB

In [50]:
df5.describe()

       product_id    brand_id  category_id   model_year    list_price
count  321.000000  321.000000   321.000000   321.000000    321.000000
mean   161.000000    5.476636     4.028037  2017.591900   1520.591402
std     92.808944    3.708131     2.188569     0.665063   1612.152765
min      1.000000    1.000000     1.000000  2016.000000     89.990000
25%     81.000000    1.000000     2.000000  2017.000000    439.990000
50%    161.000000    7.000000     3.000000  2018.000000    761.990000
75%    241.000000    9.000000     6.000000  2018.000000   2299.990000
max    321.000000    9.000000     7.000000  2019.000000  11999.990000

In [51]:
df5.isnull().sum()

product_id      0
product_name    0
brand_id        0
category_id     0
model_year      0
list_price      0
dtype: int64

In [52]:
df5.duplicated().sum()

np.int64(0)

In [54]:
df6=pd.read_csv("staffs.csv")
df6.head()

,staff_id,first_name,last_name,email,phone,active,store_id,manager_id
0,1,Fabiola,Jackson,fabiola.jackson@bikes.shop,(831) 555-5554,1,1,NaN
1,2,Mireya,Copeland,mireya.copeland@bikes.shop,(831) 555-5555,1,1,1.0
2,3,Genna,Serrano,genna.serrano@bikes.shop,(831) 555-5556,1,1,2.0
3,4,Virgie,Wiggins,virgie.wiggins@bikes.shop,(831) 555-5557,1,1,2.0
4,5,Jannette,David,jannette.david@bikes.shop,(516) 379-4444,1,2,1.0

In [55]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   staff_id    10 non-null     int64
 1   first_name  10 non-null     object
 2   last_name   10 non-null     object
 3   email       10 non-null     object
 4   phone       10 non-null     object
 5   active      10 non-null     int64
 6   store_id    10 non-null     int64
 7   manager_id  9 non-null      float64
dtypes: float64(1), int64(3), object(4)
memory usage: 772.0+ bytes

In [56]:
df6.describe()

       staff_id  active   store_id  manager_id
count  10.00000    10.0  10.000000    9.000000
mean    5.50000     1.0   1.900000    3.444444
std     3.02765     0.0   0.875595    2.554952
min     1.00000     1.0   1.000000    1.000000
25%     3.25000     1.0   1.000000    1.000000
50%     5.50000     1.0   2.000000    2.000000
75%     7.75000     1.0   2.750000    5.000000
max    10.00000     1.0   3.000000    7.000000

In [57]:
df6.isnull().sum()

staff_id      0
first_name    0
last_name     0
email         0
phone         0
active        0
store_id      0
manager_id    1
dtype: int64

In [58]:
df6.duplicated().sum()

np.int64(0)

In [59]:
df7=pd.read_csv("stocks.csv")
df7.head()

   store_id  product_id  quantity
0         1           1        27
1         1           2         5
2         1           3         6
3         1           4        23
4         1           5        22

In [60]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 939 entries, 0 to 938
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    939 non-null    int64
 1   product_id  939 non-null    int64
 2   quantity    939 non-null    int64
dtypes: int64(3)
memory usage: 22.1 KB

In [61]:
df7.describe()

         store_id  product_id    quantity
count  939.000000  939.000000  939.000000
mean     2.000000  157.000000   14.388711
std      0.816932   90.403007    8.832070
min      1.000000    1.000000    0.000000
25%      1.000000   79.000000    7.000000
50%      2.000000  157.000000   14.000000
75%      3.000000  235.000000   22.000000
max      3.000000  313.000000   30.000000

In [62]:
df7.isnull().sum()

store_id      0
product_id    0
quantity      0
dtype: int64

In [63]:
df7.duplicated().sum()

np.int64(0)

In [64]:
df8=pd.read_csv("stores.csv")
df8.head()

,store_id,store_name,phone,email,street,city,state,zip_code
0,1,Santa Cruz Bikes,(831) 476-4321,santacruz@bikes.shop,3700 Portola Drive,Santa Cruz,CA,95060
1,2,Baldwin Bikes,(516) 379-8888,baldwin@bikes.shop,4200 Chestnut Lane,Baldwin,NY,11432
2,3,Rowlett Bikes,(972) 530-5555,rowlett@bikes.shop,8000 Fairway Avenue,Rowlett,TX,75088

In [65]:
df8.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   store_id    3 non-null      int64
 1   store_name  3 non-null      object
 2   phone       3 non-null      object
 3   email       3 non-null      object
 4   street      3 non-null      object
 5   city        3 non-null      object
 6   state       3 non-null      object
 7   zip_code    3 non-null      int64
dtypes: int64(2), object(6)
memory usage: 324.0+ bytes

In [66]:
df8.describe()

       store_id      zip_code
count       3.0      3.000000
mean        2.0  60526.666667
std         1.0  43674.190517
min         1.0  11432.000000
25%         1.5  43260.000000
50%         2.0  75088.000000
75%         2.5  85074.000000
max         3.0  95060.000000

In [67]:
df8.isnull().sum()

store_id      0
store_name    0
phone         0
email         0
street        0
city          0
state         0
zip_code      0
dtype: int64

In [68]:
df8.duplicated().sum()

np.int64(0)

In [69]:
import psycopg2

In [70]:
from sqlalchemy import create_engine

In [76]:
engine_psql = create_engine("postgresql+psycopg2://postgres:ihaveaDream102@localhost:5432/bike_industry_analysis_db")

In [77]:
df.to_sql("brands",con=engine_psql,if_exists='append',index=False)
df1.to_sql("categories",con=engine_psql,if_exists='append',index=False)
df2.to_sql("customer",con=engine_psql,if_exists='append',index=False)
df3.to_sql("order_items",con=engine_psql,if_exists='append',index=False)
df4.to_sql("orders",con=engine_psql,if_exists='append',index=False)
df5.to_sql("products",con=engine_psql,if_exists='append',index=False)
df6.to_sql("staffs",con=engine_psql,if_exists='append',index=False)
df7.to_sql("stocks",con=engine_psql,if_exists='append',index=False)
df8.to_sql("stores",con=engine_psql,if_exists='append',index=False)

3